name: Update Contents JSON

on:
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC; aap isko apne hisaab se adjust kar sakte hain
  workflow_dispatch:      # Manual trigger ke liye

jobs:
  update-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Generate Contents JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain data/contents.json)" ]; then
            git add data/contents.json
            git commit -m "Update contents.json"
            git push
          else
            echo "No changes to commit."
          fi
